### ISSUE TITLE
Короче так

### ISSUE THREAD

**Issue by hinduCoder** [hinduCoder/ItdSoftwareDesign#1]
Игорь во-первых, создал классы не в проекте, а в решении. Во-вторых закоммитил вообще всё, что только можно. Нужно было коммитить только исходники. Вообще такая фигня произошла, по видимому, потому, что у тебя не .gitignore. Походу это я тупанул и добавил их в игнор. Я их запушу. Ты обновись и исправь

**Comment by hinduCoder** [comment]
> Я их запушу. Ты обновись и исправь

**Comment by bigspawn** [comment]
Надо было в начале обговорить что пушить.
